#
# This docker-compose file starts and runs:
# postgres11

version: '3.7'

services:

  postgres:
    image: postgres:11
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "cta_admin"
      POSTGRES_PASSWORD: "chicago"
      POSTGRES_DB: "cta"
    volumes:
    - ./producers/data/cta_stations.csv:/tmp
    - ./load_stations.sql:/docker-entrypoint-initdb.d/load_stations.sql
